rvm:
- 1.9.3
- 2.1.5
- 2.2.2
- 2.3.4
- 2.4.1
sudo: false
dist: trusty
cache: bundler
before_script:
  - gem update --system 2.6.12 # https://github.com/rubygems/rubygems/issues/2024
  - gem update bundler
