rvm:
- 1.9.3
sudo: false
dist: trusty
cache: bundler
install:
  - gem update --system 2.6.12  # https://github.com/rubygems/rubygems/issues/2024
  - gem update bundler
  - gem --version
  - bundle --version
  - "bundle install --verbose --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}"
