rvm:
- 1.9.3
- 2.1.5
- 2.2.7
- 2.3.4
- 2.4.1
sudo: false
dist: trusty
cache: bundler
before_script:
  - gem update --system
  - gem update bundler
install:
  - "bundle install --verbose --jobs=1 --retry=1 --path=${BUNDLE_PATH:-vendor/bundle}"
