rvm:
- 1.9.3
sudo: false
dist: trusty
cache: bundler
before_script:
  - gem uninstall bundler --all
  - gem update --system
  - gem install bundler
install:
  - "bundle install --verbose --jobs=1 --retry=1 --path=${BUNDLE_PATH:-vendor/bundle}"
