rvm:
- 1.9.3
sudo: false
dist: trusty
cache: bundler
install:
  - gem update --system 2.6.13 # Reset to failing version
  - gem update bundler
  - gem --version
  - bundle --version
  - "bundle install --verbose --jobs=1 --retry=1 --path=${BUNDLE_PATH:-vendor/bundle}"
